AWSTemplateFormatVersion: '2010-09-09'
Description: 家計簿用 Cognito User Pool

Resources:
  KakeiboUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: KakeiboUserPool
      AutoVerifiedAttributes: [email]

  KakeiboUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: KakeiboAppClient
      UserPoolId: !Ref KakeiboUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

Outputs:
  UserPoolId:
    Value: !Ref KakeiboUserPool
    Export:
      Name: KakeiboUserPoolId
  UserPoolClientId:
    Value: !Ref KakeiboUserPoolClient
    Export:
      Name: KakeiboUserPoolClientId
