AWSTemplateFormatVersion: '2010-09-09'
Description: 家計簿用 Lambda 関数と IAM ロール（CORS対応・LambdaプロキシON）

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: KakeiboLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                Resource: !Sub
                  - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}"
                  - TableName: !ImportValue KakeiboTableName

  KakeiboLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: KakeiboLambda
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue KakeiboTableName
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import uuid
          from boto3.dynamodb.conditions import Key

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table(os.environ["TABLE_NAME"])

          # ★ LambdaプロキシON時はここでCORSを返すのが唯一の正解
          CORS_HEADERS = {
              "Access-Control-Allow-Origin": "*",
              "Access-Control-Allow-Headers": "Content-Type,Authorization",
              "Access-Control-Allow-Methods": "OPTIONS,GET,POST"
          }

          def handler(event, context):
              try:
                  method = event.get("httpMethod")

                  # preflight（OPTIONS）
                  if method == "OPTIONS":
                      return {
                          "statusCode": 200,
                          "headers": CORS_HEADERS,
                          "body": ""
                      }

                  userId = event["requestContext"]["authorizer"]["claims"]["sub"]

                  # 一覧取得
                  if method == "GET":
                      resp = table.query(
                          KeyConditionExpression=Key("userId").eq(userId)
                      )
                      return {
                          "statusCode": 200,
                          "headers": CORS_HEADERS,
                          "body": json.dumps(resp.get("Items", []))
                      }

                  # 追加
                  elif method == "POST":
                      body = json.loads(event.get("body", "{}"))
                      entryId = str(uuid.uuid4())

                      table.put_item(
                          Item={
                              "userId": userId,
                              "entryId": entryId,
                              "date": body.get("date"),
                              "item": body.get("item"),
                              "amount": body.get("amount")
                          }
                      )

                      resp = table.query(
                          KeyConditionExpression=Key("userId").eq(userId)
                      )

                      return {
                          "statusCode": 200,
                          "headers": CORS_HEADERS,
                          "body": json.dumps(resp.get("Items", []))
                      }

                  else:
                      return {
                          "statusCode": 400,
                          "headers": CORS_HEADERS,
                          "body": "Unsupported method"
                      }

              except Exception as e:
                  return {
                      "statusCode": 500,
                      "headers": CORS_HEADERS,
                      "body": json.dumps({"error": str(e)})
                  }

Outputs:
  LambdaArn:
    Value: !GetAtt KakeiboLambda.Arn
    Export:
      Name: KakeiboLambdaArn
